### ISSUE TITLE
Enhancement - option to strip gpx uploads of <ele> <time> tags

### ISSUE THREAD

**Issue by tasker25** [sfreytag/simonlikesmaps#49]
If I upload a gpx file I have recorded on my gps or found elsewhere in order to create a route, I may want to make slight modifications. I can move existing trackpoints, but if the file contains \<ele\> \<time\> or \<speed\> tags, your program does not allow me to ADD new trackpoints. I see the logic of this since it would create a mixed file with only some points having this extra data. However, since the purpose of the upload is to create a usable route this is an annoying limitation. You already have a facility to reduce the number of trackpoints when uploading. Could you add an option to strip out extraneous tags leaving just the position. You would then be able to edit the route in SLM by adding waypoints as well as moving existing ones. At the moment I am having to use a separate gpx editor to remove the extra tags from my gpx file before I upload it.

Martin Burnell

**Comment by sfreytag** [comment]
I'm also finding issues with various GPX files I download off the internet and try to upload to SLM to edit them further. I don't know for sure but it feels like GPX files have got more complex, or at least I encounter more issues now. So I'd also like to dig into this a bit more too. However you might have found a more specific bug - it is interesting that it uploads and can be edited, but not added to. I generally see either total failure, or all working!

Would you be able to attach an example file to this issue so I can  test with it?

Most likely a proper fix will come with the upcoming rebuild of SLM as a brand new version, the motivation mostly being to fixi a lot of the small bugs that hang around by upgrading the software behind the app - bit more info here: https://github.com/sfreytag/simonlikesmaps/discussions/43

However, this might be easy to fix for the current site, in which case I'll give it a go.

**Comment by sfreytag** [comment]
Discussions now closed - use #50 for anything general.

**Comment by sfreytag** [comment]
that's good news. I'll keep this issue open to make sure it still works once I add the function to upload GPX files to the new version. 

I am not entirely sure where/how this problem would have been fixed in the new version, so I'd like to think it validates the approach of building a new version with modern code to get more reliable software that fixes a lot of the glitches in the old version.

**Comment by sfreytag** [comment]
A GPX import function is being released shortly... I have tested it with GPX files that use `<rte>` and with files that use `<trk>`, and have also been testing with a GPX generated from Strava from a FIT file off my Suunto watch. This includes plenty of extraneous data - elevation, time and extensions for temperature and cadence:

```
   <trkpt lat="53.3609810" lon="-2.0051860">
    <ele>168.0</ele>
    <time>2024-02-11T14:55:30Z</time>
    <extensions>
     <gpxtpx:TrackPointExtension>
      <gpxtpx:atemp>22</gpxtpx:atemp>
      <gpxtpx:cad>78</gpxtpx:cad>
     </gpxtpx:TrackPointExtension>
    </extensions>
   </trkpt>
```

In all cases, the extra data is stripped and just the Lat/Lng coords are imported into your plan.

If the GPX is a <trk> and contains multiple <trkseg> then just the first segment is imported as the route. However it would be doable to work through all the <trkseg>s and import them one by one as individual routes within the plan. I'm not sure this is useful, though. Alternatively I could attempt to list the segments and let you pick which one to import. But to do that they'd all need displaying on the map I think, to recognise which is which. So if doing that then I may as well just import them all and let the user remove the ones they don't want using the existing tools. I will keep this in mind and can add it in future if it turns out to be needed.

I'll close this now, but if you have any GPX files that cause issues then add them to a new issue - it would be great to get this reliable again. The increasing failure to import GPX files was one of the things frustrating me the most about old SLM.
